# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import common_pb2 as common__pb2
import order_bill_pb2 as order__bill__pb2
import order_operation_log_pb2 as order__operation__log__pb2
import order_package_pb2 as order__package__pb2
import order_pb2 as order__pb2
import order_settlement_pb2 as order__settlement__pb2


class OrderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateOrder = channel.unary_unary(
                '/order.OrderService/CreateOrder',
                request_serializer=order__pb2.OrderCreateReq.SerializeToString,
                response_deserializer=order__pb2.OrderCreateResult.FromString,
                )
        self.CreateMerchantOrder = channel.unary_unary(
                '/order.OrderService/CreateMerchantOrder',
                request_serializer=order__pb2.MerchantOrderCreateReq.SerializeToString,
                response_deserializer=order__pb2.MerchantOrderCreateResult.FromString,
                )
        self.GetOrderList = channel.unary_unary(
                '/order.OrderService/GetOrderList',
                request_serializer=common__pb2.QueryInfo.SerializeToString,
                response_deserializer=order__pb2.OrderListResult.FromString,
                )
        self.UpdateOrderByAction = channel.unary_unary(
                '/order.OrderService/UpdateOrderByAction',
                request_serializer=order__pb2.OrderUpdateContent.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                )
        self.CreateBill = channel.unary_unary(
                '/order.OrderService/CreateBill',
                request_serializer=order__bill__pb2.OrderBillCreateReq.SerializeToString,
                response_deserializer=order__bill__pb2.OrderBillCreateResult.FromString,
                )
        self.GetBillList = channel.unary_unary(
                '/order.OrderService/GetBillList',
                request_serializer=common__pb2.QueryInfo.SerializeToString,
                response_deserializer=order__bill__pb2.OrderBillListResult.FromString,
                )
        self.GetOrderOperationLogList = channel.unary_unary(
                '/order.OrderService/GetOrderOperationLogList',
                request_serializer=common__pb2.QueryInfo.SerializeToString,
                response_deserializer=order__operation__log__pb2.OrderOperationLogListResult.FromString,
                )
        self.GetPackageList = channel.unary_unary(
                '/order.OrderService/GetPackageList',
                request_serializer=common__pb2.QueryInfo.SerializeToString,
                response_deserializer=order__package__pb2.OrderPackageListResult.FromString,
                )
        self.GetSettlementList = channel.unary_unary(
                '/order.OrderService/GetSettlementList',
                request_serializer=common__pb2.QueryInfo.SerializeToString,
                response_deserializer=order__settlement__pb2.OrderSettlementListResultV2.FromString,
                )


class OrderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateOrder(self, request, context):
        """订单
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMerchantOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateOrderByAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBill(self, request, context):
        """账单
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBillList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderOperationLogList(self, request, context):
        """操作日志
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPackageList(self, request, context):
        """物流相关，V2兼容V1，后期接入TMS后可废弃
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSettlementList(self, request, context):
        """结算
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrder,
                    request_deserializer=order__pb2.OrderCreateReq.FromString,
                    response_serializer=order__pb2.OrderCreateResult.SerializeToString,
            ),
            'CreateMerchantOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMerchantOrder,
                    request_deserializer=order__pb2.MerchantOrderCreateReq.FromString,
                    response_serializer=order__pb2.MerchantOrderCreateResult.SerializeToString,
            ),
            'GetOrderList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderList,
                    request_deserializer=common__pb2.QueryInfo.FromString,
                    response_serializer=order__pb2.OrderListResult.SerializeToString,
            ),
            'UpdateOrderByAction': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateOrderByAction,
                    request_deserializer=order__pb2.OrderUpdateContent.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
            'CreateBill': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBill,
                    request_deserializer=order__bill__pb2.OrderBillCreateReq.FromString,
                    response_serializer=order__bill__pb2.OrderBillCreateResult.SerializeToString,
            ),
            'GetBillList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBillList,
                    request_deserializer=common__pb2.QueryInfo.FromString,
                    response_serializer=order__bill__pb2.OrderBillListResult.SerializeToString,
            ),
            'GetOrderOperationLogList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderOperationLogList,
                    request_deserializer=common__pb2.QueryInfo.FromString,
                    response_serializer=order__operation__log__pb2.OrderOperationLogListResult.SerializeToString,
            ),
            'GetPackageList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPackageList,
                    request_deserializer=common__pb2.QueryInfo.FromString,
                    response_serializer=order__package__pb2.OrderPackageListResult.SerializeToString,
            ),
            'GetSettlementList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSettlementList,
                    request_deserializer=common__pb2.QueryInfo.FromString,
                    response_serializer=order__settlement__pb2.OrderSettlementListResultV2.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'order.OrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/CreateOrder',
            order__pb2.OrderCreateReq.SerializeToString,
            order__pb2.OrderCreateResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateMerchantOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/CreateMerchantOrder',
            order__pb2.MerchantOrderCreateReq.SerializeToString,
            order__pb2.MerchantOrderCreateResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrderList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/GetOrderList',
            common__pb2.QueryInfo.SerializeToString,
            order__pb2.OrderListResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateOrderByAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/UpdateOrderByAction',
            order__pb2.OrderUpdateContent.SerializeToString,
            common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateBill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/CreateBill',
            order__bill__pb2.OrderBillCreateReq.SerializeToString,
            order__bill__pb2.OrderBillCreateResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBillList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/GetBillList',
            common__pb2.QueryInfo.SerializeToString,
            order__bill__pb2.OrderBillListResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrderOperationLogList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/GetOrderOperationLogList',
            common__pb2.QueryInfo.SerializeToString,
            order__operation__log__pb2.OrderOperationLogListResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPackageList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/GetPackageList',
            common__pb2.QueryInfo.SerializeToString,
            order__package__pb2.OrderPackageListResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSettlementList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/GetSettlementList',
            common__pb2.QueryInfo.SerializeToString,
            order__settlement__pb2.OrderSettlementListResultV2.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
