# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_operation_log.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import code_pb2 as code__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='order_operation_log.proto',
  package='order',
  syntax='proto3',
  serialized_options=b'Z\027app/protocol/grpc/order',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19order_operation_log.proto\x12\x05order\x1a\ncode.proto\"\x93\x01\n\x11OrderOperationLog\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\toperation\x18\x02 \x01(\t\x12\x0e\n\x06remark\x18\x03 \x01(\t\x12\x13\n\x0boperator_id\x18\x04 \x01(\t\x12\x15\n\roperator_name\x18\x05 \x01(\t\x12\x11\n\tcreate_at\x18\x06 \x01(\x03\x12\x10\n\x08order_id\x18\x07 \x01(\t\"{\n\x1bOrderOperationLogListResult\x12&\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x18.order.OrderOperationLog\x12\r\n\x05total\x18\x02 \x01(\x03\x12\x18\n\x04\x63ode\x18\x03 \x01(\x0e\x32\n.code.Code\x12\x0b\n\x03msg\x18\x04 \x01(\tB\x19Z\x17\x61pp/protocol/grpc/orderb\x06proto3'
  ,
  dependencies=[code__pb2.DESCRIPTOR,])




_ORDEROPERATIONLOG = _descriptor.Descriptor(
  name='OrderOperationLog',
  full_name='order.OrderOperationLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='order.OrderOperationLog.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operation', full_name='order.OrderOperationLog.operation', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='remark', full_name='order.OrderOperationLog.remark', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operator_id', full_name='order.OrderOperationLog.operator_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operator_name', full_name='order.OrderOperationLog.operator_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='create_at', full_name='order.OrderOperationLog.create_at', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='order_id', full_name='order.OrderOperationLog.order_id', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=196,
)


_ORDEROPERATIONLOGLISTRESULT = _descriptor.Descriptor(
  name='OrderOperationLogListResult',
  full_name='order.OrderOperationLogListResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='order.OrderOperationLogListResult.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total', full_name='order.OrderOperationLogListResult.total', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='order.OrderOperationLogListResult.code', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='order.OrderOperationLogListResult.msg', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=321,
)

_ORDEROPERATIONLOGLISTRESULT.fields_by_name['data'].message_type = _ORDEROPERATIONLOG
_ORDEROPERATIONLOGLISTRESULT.fields_by_name['code'].enum_type = code__pb2._CODE
DESCRIPTOR.message_types_by_name['OrderOperationLog'] = _ORDEROPERATIONLOG
DESCRIPTOR.message_types_by_name['OrderOperationLogListResult'] = _ORDEROPERATIONLOGLISTRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrderOperationLog = _reflection.GeneratedProtocolMessageType('OrderOperationLog', (_message.Message,), {
  'DESCRIPTOR' : _ORDEROPERATIONLOG,
  '__module__' : 'order_operation_log_pb2'
  # @@protoc_insertion_point(class_scope:order.OrderOperationLog)
  })
_sym_db.RegisterMessage(OrderOperationLog)

OrderOperationLogListResult = _reflection.GeneratedProtocolMessageType('OrderOperationLogListResult', (_message.Message,), {
  'DESCRIPTOR' : _ORDEROPERATIONLOGLISTRESULT,
  '__module__' : 'order_operation_log_pb2'
  # @@protoc_insertion_point(class_scope:order.OrderOperationLogListResult)
  })
_sym_db.RegisterMessage(OrderOperationLogListResult)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
