# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import order_pb2 as order__pb2
import order_bill_pb2 as order__bill__pb2
import order_operation_log_pb2 as order__operation__log__pb2
import order_package_pb2 as order__package__pb2
import order_settlement_pb2 as order__settlement__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='order_service.proto',
  package='order',
  syntax='proto3',
  serialized_options=b'Z\027app/protocol/grpc/order',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13order_service.proto\x12\x05order\x1a\x0border.proto\x1a\x10order_bill.proto\x1a\x19order_operation_log.proto\x1a\x13order_package.proto\x1a\x16order_settlement.proto\x1a\x0c\x63ommon.proto2\x8a\x05\n\x0cOrderService\x12>\n\x0b\x43reateOrder\x12\x15.order.OrderCreateReq\x1a\x18.order.OrderCreateResult\x12V\n\x13\x43reateMerchantOrder\x12\x1d.order.MerchantOrderCreateReq\x1a .order.MerchantOrderCreateResult\x12\x39\n\x0cGetOrderList\x12\x11.common.QueryInfo\x1a\x16.order.OrderListResult\x12?\n\x13UpdateOrderByAction\x12\x19.order.OrderUpdateContent\x1a\r.common.Empty\x12\x45\n\nCreateBill\x12\x19.order.OrderBillCreateReq\x1a\x1c.order.OrderBillCreateResult\x12<\n\x0bGetBillList\x12\x11.common.QueryInfo\x1a\x1a.order.OrderBillListResult\x12Q\n\x18GetOrderOperationLogList\x12\x11.common.QueryInfo\x1a\".order.OrderOperationLogListResult\x12\x42\n\x0eGetPackageList\x12\x11.common.QueryInfo\x1a\x1d.order.OrderPackageListResult\x12J\n\x11GetSettlementList\x12\x11.common.QueryInfo\x1a\".order.OrderSettlementListResultV2B\x19Z\x17\x61pp/protocol/grpc/orderb\x06proto3'
  ,
  dependencies=[order__pb2.DESCRIPTOR,order__bill__pb2.DESCRIPTOR,order__operation__log__pb2.DESCRIPTOR,order__package__pb2.DESCRIPTOR,order__settlement__pb2.DESCRIPTOR,common__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_ORDERSERVICE = _descriptor.ServiceDescriptor(
  name='OrderService',
  full_name='order.OrderService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=148,
  serialized_end=798,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateOrder',
    full_name='order.OrderService.CreateOrder',
    index=0,
    containing_service=None,
    input_type=order__pb2._ORDERCREATEREQ,
    output_type=order__pb2._ORDERCREATERESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateMerchantOrder',
    full_name='order.OrderService.CreateMerchantOrder',
    index=1,
    containing_service=None,
    input_type=order__pb2._MERCHANTORDERCREATEREQ,
    output_type=order__pb2._MERCHANTORDERCREATERESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetOrderList',
    full_name='order.OrderService.GetOrderList',
    index=2,
    containing_service=None,
    input_type=common__pb2._QUERYINFO,
    output_type=order__pb2._ORDERLISTRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateOrderByAction',
    full_name='order.OrderService.UpdateOrderByAction',
    index=3,
    containing_service=None,
    input_type=order__pb2._ORDERUPDATECONTENT,
    output_type=common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateBill',
    full_name='order.OrderService.CreateBill',
    index=4,
    containing_service=None,
    input_type=order__bill__pb2._ORDERBILLCREATEREQ,
    output_type=order__bill__pb2._ORDERBILLCREATERESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetBillList',
    full_name='order.OrderService.GetBillList',
    index=5,
    containing_service=None,
    input_type=common__pb2._QUERYINFO,
    output_type=order__bill__pb2._ORDERBILLLISTRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetOrderOperationLogList',
    full_name='order.OrderService.GetOrderOperationLogList',
    index=6,
    containing_service=None,
    input_type=common__pb2._QUERYINFO,
    output_type=order__operation__log__pb2._ORDEROPERATIONLOGLISTRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetPackageList',
    full_name='order.OrderService.GetPackageList',
    index=7,
    containing_service=None,
    input_type=common__pb2._QUERYINFO,
    output_type=order__package__pb2._ORDERPACKAGELISTRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetSettlementList',
    full_name='order.OrderService.GetSettlementList',
    index=8,
    containing_service=None,
    input_type=common__pb2._QUERYINFO,
    output_type=order__settlement__pb2._ORDERSETTLEMENTLISTRESULTV2,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ORDERSERVICE)

DESCRIPTOR.services_by_name['OrderService'] = _ORDERSERVICE

# @@protoc_insertion_point(module_scope)
