# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_review.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='order_review.proto',
  package='order',
  syntax='proto3',
  serialized_options=b'Z\027app/protocol/grpc/order',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12order_review.proto\x12\x05order\"M\n\x0fOrderReviewInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x0e\n\x06remark\x18\x03 \x01(\t\x12\x0e\n\x06result\x18\x04 \x01(\tB\x19Z\x17\x61pp/protocol/grpc/orderb\x06proto3'
)




_ORDERREVIEWINFO = _descriptor.Descriptor(
  name='OrderReviewInfo',
  full_name='order.OrderReviewInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='order.OrderReviewInfo.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='method', full_name='order.OrderReviewInfo.method', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='remark', full_name='order.OrderReviewInfo.remark', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='order.OrderReviewInfo.result', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['OrderReviewInfo'] = _ORDERREVIEWINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrderReviewInfo = _reflection.GeneratedProtocolMessageType('OrderReviewInfo', (_message.Message,), {
  'DESCRIPTOR' : _ORDERREVIEWINFO,
  '__module__' : 'order_review_pb2'
  # @@protoc_insertion_point(class_scope:order.OrderReviewInfo)
  })
_sym_db.RegisterMessage(OrderReviewInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
